apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: management-gitops-hypershift-rhacm
rules:
  # HyperShift hosted control planes
  - apiGroups: ["hypershift.openshift.io"]
    resources: ["hostedclusters", "nodepools"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # RHACM managed clusters
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # RHACM klusterlet addon configs (namespaced)
  - apiGroups: ["agent.open-cluster-management.io"]
    resources: ["klusterletaddonconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Projects (cluster-scoped)
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Secrets in the cluster-config namespaces (here: 'clusters' and maybe 'my-hosted-cluster')
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
